[package]
name = "ya-gpt-cli"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
anyhow.workspace = true
clap = { workspace = true, features = ["derive"] }
rand.workspace = true
serde_json.workspace = true
ya-gpt = { path = "../core", features = ["clap"] }
ya-gpt-cuda = { path = "../cuda", optional = true }

[features]
cuda = ["ya-gpt-cuda"]
simd-wide = ["ya-gpt/simd-wide"]
